services:

  aiometadata:
    image: "ghcr.io/cedya77/aiometadata:latest"
    container_name: "aiometadata"
    hostname: "aiometadata"
    restart: "unless-stopped"
    ports:
      - "3008:1337"
    volumes:
      - "${HOME}/AIOMetaData:/app/addon/data"
    environment:
      - "TZ=Europe/London"
      - "PORT=1337"
      - "HOST_NAME=https://aiometadata.jimeagle.com"
      - "NODE_ENV=production"
      - "REDIS_URL=redis://redis:6379"
      - "DATABASE_URI=sqlite://addon/data/db.sqlite"

  aiostreams:
    image: "ghcr.io/viren070/aiostreams:latest"
    container_name: "aiostreams"
    hostname: "aiostreams"
    restart: "unless-stopped"
    ports:
      - "3007:3000"
    environment:
      - "TZ=Europe/London"
      - "LOG_TIMEZONE=Europe/London"
      - "ADDON_NAME=Seven"
      - "ADDON_ID=aiostreams.jimeagle.com"
      - "BASE_URL=https://aiostreams.jimeagle.com"
      - "SECRET_KEY=${AIO_SECRET_KEY}"
    volumes:
      - "${HOME}/AIOStreams:/app/data"

  nzbdav:
    image: "nzbdav/nzbdav:latest"
    container_name: "nzbdav"
    hostname: "nzbdav"
    restart: "unless-stopped"
    ports:
      - "3010:3000"
    environment:
      - "PUID=1000"
      - "PGID=1000"
    volumes:
      - "${HOME}/NzbDav:/config"

  usenet-ultimate:
    image: "ghcr.io/dsmart33/usenet-ultimate:latest"
    container_name: "usenet-ultimate"
    hostname: "usenet-ultimate"
    restart: "unless-stopped"
    ports:
      - "1338:1338"
    volumes:
      - "${HOME}/UsenetUltimate:/app/config"
    environment:
      - "PORT=1338"

  #  realdebrid:
  #    image: "rogerfar/rdtclient:latest"
  #    container_name: "realdebrid"
  #    hostname: "realdebrid"
  #    restart: "unless-stopped"
  #    ports:
  #      - "6500:6500"
  #    environment:
  #      - "PUID=1000"
  #      - "PGID=1000"
  #      - "TZ=Europe/London"
  #    volumes:
  #      - "${HOME}/RealDebrid/DB:/data/db"
  #      - "${HOME}/RealDebrid/Downloads:/data/downloads"
