---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Smart Home:
    - Home Assistant:
        href: https://hass.jimeagle.com/
        container: hass
    - Node-RED:
        href: https://nodered.jimeagle.com/
        container: nodered
    - Frigate:
        href: https://frigate.jimeagle.com/
        container: frigate

- Network:
    - AdGuard:
        href: https://adguard.jimeagle.com/
        container: adguard
    - Uptime Kuma:
        href: https://kuma.jimeagle.com/
        container: kuma
    - Beszel:
        href: https://beszel.jimeagle.com/
        container: beszel
    - Change Detection:
        href: https://changedetection.jimeagle.com/
        container: changedetection
    - Router:
        href: https://router.jimeagle.com/

- Media:
    - Sonarr:
        href: https://sonarr.jimeagle.com/
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: {{HOMEPAGE_VAR_SONARR}}
    - Radarr:
        href: https://radarr.jimeagle.com/
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: {{HOMEPAGE_VAR_RADARR}}
    - Prowlarr:
        href: https://prowlarr.jimeagle.com/
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: {{HOMEPAGE_VAR_PROWLARR}}
    - Overseerr:
        href: https://overseerr.jimeagle.com/
        container: overseerr
        widget:
          type: overseerr
          url: http://overseerr:5055
          key: {{HOMEPAGE_VAR_OVERSEERR}}
    - NZBGet:
        href: https://nzbget.jimeagle.com/
        container: nzbget
        widget:
          type: nzbget
          url: http://nzbget:6789
          username: {{HOMEPAGE_VAR_NZBGET_UN}}
          password: {{HOMEPAGE_VAR_NZBGET_PW}}
    - RealDebrid:
        href: https://realdebrid.jimeagle.com/
        container: realdebrid
    - Maintainerr:
        href: https://maintainerr.jimeagle.com/
        container: maintainerr

- Stremio:
    - AIO Metadata:
        href: https://aiometadata.jimeagle.com/
        container: aiometadata
    - AIO Streams:
        href: https://aiostreams.jimeagle.com/
        container: aiostreams

- Tools:
    - Slink:
        href: https://slink.jimeagle.com/
        container: slink
    - Strava:
        href: https://strava.jimeagle.com/
        container: strava
